version: '3'
services:
  web:
    container_name: forgEtsy-docker-node
    restart: always
    build: .
    ports:
      - '80:3002'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'